[package]
name = "hex_to_uf2"
version = "0.1.0"
edition = "2021"
license = "AGPLv3"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", optional = true }

[features]
default = []
clap = ["dep:clap"]
