[package]
readme = "README.md"
repository = "https://git.sr.ht/~fenris/hex-to-uf2"
description = "Convert hex to uf2"
license-file = "LICENSE.md"

[workspace]
members = [
    "hex_to_uf2",
    "cargo_hex_to_uf2",
]
