[package]
name = "cargo-hex-to-uf2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
hex_to_uf2 = { path = "../hex_to_uf2", features=["clap"] }
